name: real-time-flights-ingestion

services:
  web-server:
    image: rtfi/web-server:latest
    container_name: web-server
    build: ./
    secrets:
      - source: api-key
        target: api_key # mounted to /run/secrets/api_key
    ports:
      - 8080:8080

secrets:
  api-key:
    file: ./api_key
